import { XP_RULES } from "./stats.constants";

export const LEADERBOARD_RULES = {
  DEFAULT_WORD_DIFFICULTY: XP_RULES.DEFAULT_WORD_DIFFICULTY,
  HARD_WORD_DIFFICULTY_THRESHOLD: XP_RULES.HARD_WORD_DIFFICULTY_THRESHOLD,
  PERCENT_MULTIPLIER: 100,
  ACCURACY_DECIMAL_PLACES: 1,
  RANK_START: 1,
} as const;
