import { LEARNING_MASTERY_LEVEL, LEARNING_STRENGTH } from "./learning.constants";

export const QUIZ_CANDIDATE_SCORING = {
  NEW_WORD_DIFFICULTY_MULTIPLIER: 2,
  NEW_WORD_BASE_BOOST: 50,
  WRONG_COUNT_WEIGHT: 2,
  DIRECTION_WEAKNESS_SCALE: 8,
  MASTERED_NOT_DUE_PENALTY: -1000,
  DAYS_SINCE_LAST_SEEN_DIVISOR_MS: 1000 * 60 * 60 * 24,
  DEFAULT_WORD_DIFFICULTY: 1,
  MASTERED_MIN_LEVEL: LEARNING_MASTERY_LEVEL.MASTERED_MIN,
  DEFAULT_DIRECTION_STRENGTH: LEARNING_STRENGTH.DEFAULT,
} as const;
