import { LEARNING_STRENGTH } from "./learning.constants";

export const SRS_QUALITY_RULES = {
  INCORRECT_QUALITY: 1,
  BASE_QUALITY: 3,
  HIGH_CONFIDENCE_THRESHOLD: 3,
  LOW_CONFIDENCE_THRESHOLD: 1,
  HIGH_CONFIDENCE_BONUS: 1,
  LOW_CONFIDENCE_PENALTY: 0.5,
  FAST_RESPONSE_MS_THRESHOLD: 3000,
  SLOW_RESPONSE_MS_THRESHOLD: 10000,
  FAST_RESPONSE_BONUS: 0.5,
  SLOW_RESPONSE_PENALTY: 0.5,
  QUALITY_MIN: 0,
  QUALITY_MAX: 5,
} as const;

export const SRS_MASTERY_RULES = {
  SECOND_STREAK_STEP: 2,
  LEVEL_4_STREAK_MIN: 7,
  LEVEL_3_STREAK_MIN: 5,
  LEVEL_2_STREAK_MIN: 3,
  LEVEL_1_STREAK_MIN: 1,
} as const;

export const SRS_STRENGTH_RULES = {
  CORRECT_BASE_ADJUSTMENT: 0.12,
  INCORRECT_BASE_ADJUSTMENT: -0.18,
  CORRECT_CONFIDENCE_SCALE: 0.04,
  INCORRECT_CONFIDENCE_SCALE: 0.02,
  DEFAULT_STRENGTH: LEARNING_STRENGTH.DEFAULT,
  MIN_STRENGTH: 0,
  MAX_STRENGTH: 1,
  CONFIDENCE_BASELINE: 2,
} as const;

export const SRS_DEFAULT_CONFIG = {
  VERSION: "v1",
  EASE_MIN: 1.3,
  EASE_MAX: 3.0,
  INCORRECT_EASE_PENALTY: 0.2,
  DEFAULT_EASE: 2.5,
  DEFAULT_INTERVAL_DAYS: 1,
  SECOND_INTERVAL_DAYS: 6,
  QUALITY_PASS_THRESHOLD: 3,
} as const;

export const SRS_EASE_UPDATE = {
  BASE_INCREMENT: 0.1,
  QUALITY_OFFSET: 5,
  PRIMARY_FACTOR: 0.08,
  SECONDARY_FACTOR: 0.02,
} as const;
