import { API_PAGINATION_DEFAULTS } from "@shared/domain/api-limits";

export const STORAGE_RULES = {
  SRS_HIGH_INTERVAL_THRESHOLD_DAYS: 45,
  EMPTY_REVIEW_DAYS_FALLBACK: 999,
  MILLISECONDS_PER_DAY: 1000 * 60 * 60 * 24,
  DEFAULT_REVIEW_QUEUE_LIMIT: API_PAGINATION_DEFAULTS.REVIEW_LIMIT,
  PERCENT_MULTIPLIER: 100,
  ONE_DECIMAL_PLACE: 1,
} as const;
