export const API_PAGINATION_DEFAULTS = {
  PAGE: 1,
  QUIZ_COUNT: 10,
  WORD_BUCKET_LIMIT: 50,
  ATTEMPT_HISTORY_LIMIT: 100,
  LEADERBOARD_LIMIT: 25,
  REVIEW_LIMIT: 50,
} as const;

export const API_PAGINATION_LIMITS = {
  GENERIC_MAX: 200,
  LEADERBOARD_MAX: 100,
} as const;

export const API_VALIDATION_LIMITS = {
  FEEDBACK_SUBJECT_MIN: 3,
  FEEDBACK_SUBJECT_MAX: 120,
  FEEDBACK_MESSAGE_MIN: 10,
  FEEDBACK_MESSAGE_MAX: 4000,
  REVIEW_NOTES_MAX: 1000,
  BULK_IDS_MIN: 1,
  BULK_IDS_MAX: 200,
  EXAMPLE_DIFFICULTY_MIN: 1,
  EXAMPLE_DIFFICULTY_MAX: 5,
  REVIEWER_CONFIDENCE_MIN: 1,
  REVIEWER_CONFIDENCE_MAX: 5,
} as const;
